version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "gh-actions"
      - "dependencies"
    reviewers:
      - cristiadu

  # Maintain dependencies for pnpm workspaces
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
    reviewers:
      - cristiadu
