version: 2
updates:
  # 🧩 Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "gh-actions"
      - "dependencies"
    groups:
      all-github-actions:
        patterns:
          - "*"

  # 🪄 Maintain dependencies for pnpm workspaces (API + UI + root)
  - package-ecosystem: "npm" # Dependabot uses npm for pnpm projects
    directory: "/"           # Root where pnpm-lock.yaml lives
    schedule:
      interval: "monthly"
    labels:
      - "npm"
      - "dependencies"
    groups:
      all-pnpm-dependencies:
        patterns:
          - "*"
