name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        package_json_file: package.json
        run_install: false
    - name: Use Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: '.nvmrc'
        cache: pnpm
        cache-dependency-path: "pnpm-lock.yaml"

    - name: Install Projects' Dependencies
      run: |
        pnpm install
        
    - name: Build Projects
      run: |
        pnpm build

    - name: Lint Projects
      run: |
        pnpm lint

    - name: Test Projects
      run: |
        pnpm create-env-file
        pnpm test

    - name: Checking for unused code and dependencies
      run: |
        pnpm knip
