name: Publish Packages to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  version-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.7.1
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@${{ github.repository_owner }}'
          cache: 'pnpm'
          cache-dependency-path: "pnpm-lock.yaml"
      
      - name: Install Dependencies
        run: pnpm install
      
      - name: Build All
        run: pnpm build
      
      # Create a release PR or publish directly based on changesets
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm version-packages
          publish: pnpm release
          commit: "chore: version packages"
          title: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Only run this step if changesets published versions
      - name: Setup .npmrc and publish packages if versions were bumped
        if: steps.changesets.outputs.published == 'true'
        run: |
          # Create .npmrc file but don't commit it
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          echo "@${{ github.repository_owner }}:registry=https://npm.pkg.github.com" >> .npmrc
          
          # The actual publish happens elsewhere, this is just for any follow-up tasks
          echo "Packages were published successfully!"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 